version: '3'
services:
  api:
    build: .
    volumes:
      - .:/srv/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ""
      DATABASE_NAME: routine_transactions

  db:
    image: postgres:11.7-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - db

